### ISSUE TITLE
Carousel Bootstrap - Problème d'affichage

### ISSUE THREAD

**Issue by Tawagot0** [JorisGit/SOS_Partners#1]
Problème en responsive du carousel, en réduisant la fenêtre l'affichage ne se fait pas correctement.

![screenshot_1](https://cloud.githubusercontent.com/assets/26726263/25506137/782e6ff8-2ba5-11e7-94ca-cd5a5bcb0cea.png)

**Comment by JorisGit** [comment]
Suprression du carrousel.

**Comment by Tawagot0** [comment]
Suppression du carrousel.
